development:
  host: localhost
  database: paper_development

test:
  host: localhost
  database: paper_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>

