development:
  host: <%= ENV['PAPER_HOST'] %>
  time_zone: <%= ENV['PAPER_TIME_ZONE'] %>
  owner:
    name: <%= ENV['PAPER_OWNER_NAME'] %>
    email: <%= ENV['PAPER_OWNER_EMAIL'] %>
    password: <%= ENV['PAPER_OWNER_PASSWORD'] %>
  recaptcha:
    public_key: <%= ENV['PAPER_RECAPTCHA_PUBLIC'] %>
    private_key: <%= ENV['PAPER_RECAPTCHA_PRIVATE'] %>

test:
  host: <%= ENV['PAPER_HOST'] %>
  time_zone: <%= ENV['PAPER_TIME_ZONE'] %>
  owner:
    name: <%= ENV['PAPER_OWNER_NAME'] %>
    email: <%= ENV['PAPER_OWNER_EMAIL'] %>
    password: <%= ENV['PAPER_OWNER_PASSWORD'] %>
  recaptcha:
    public_key: <%= ENV['PAPER_RECAPTCHA_PUBLIC'] %>
    private_key: <%= ENV['PAPER_RECAPTCHA_PRIVATE'] %>

production:
  host: <%= ENV['PAPER_HOST'] %>
  time_zone: <%= ENV['PAPER_TIME_ZONE'] %>
  owner:
    name: <%= ENV['PAPER_OWNER_NAME'] %>
    email: <%= ENV['PAPER_OWNER_EMAIL'] %>
    password: <%= ENV['PAPER_OWNER_PASSWORD'] %>
  recaptcha:
    public_key: <%= ENV['PAPER_RECAPTCHA_PUBLIC'] %>
    private_key: <%= ENV['PAPER_RECAPTCHA_PRIVATE'] %>